"""Initial schema — three core tables for the finance MCP.

Hand-written (not autogenerated) for full auditability. The CREATE TABLE
statements mirror exactly what the ORM models declare, so autogenerate will
produce no diff after this migration is applied.

Revision ID: 0001
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    # ------------------------------------------------------------------ symbols
    op.create_table(
        "symbols",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(20), nullable=False),
        sa.Column("exchange", sa.String(20), nullable=False),
        sa.Column("isin", sa.String(12), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "asset_class",
            sa.String(20),
            nullable=True,
            comment="e.g. 'STOCK', 'ETF'",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "exchange", name="uq_symbols_ticker_exchange"),
    )
    # Non-unique index on ISIN — same ISIN can list on multiple exchanges
    op.create_index("ix_symbols_isin", "symbols", ["isin"])

    # -------------------------------------------------------------- ohlcv_daily
    op.create_table(
        "ohlcv_daily",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(18, 6), nullable=False),
        sa.Column("high", sa.Numeric(18, 6), nullable=False),
        sa.Column("low", sa.Numeric(18, 6), nullable=False),
        sa.Column("close", sa.Numeric(18, 6), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column(
            "source",
            sa.String(30),
            nullable=False,
            comment="e.g. 'yfinance', 'twelve_data'",
        ),
        sa.ForeignKeyConstraint(["symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol_id", "date", "source", name="uq_ohlcv_symbol_date_source"
        ),
    )
    # Composite index supporting fast range queries per symbol
    op.create_index(
        "ix_ohlcv_symbol_date_desc",
        "ohlcv_daily",
        ["symbol_id", "date"],
    )

    # --------------------------------------------------------- fundamentals_cache
    op.create_table(
        "fundamentals_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol_id", "as_of_date", name="uq_fundamentals_symbol_date"
        ),
    )
    # Descending composite index for fast "get latest snapshot" queries
    op.create_index(
        "ix_fundamentals_symbol_date_desc",
        "fundamentals_cache",
        ["symbol_id", "as_of_date"],
    )


def downgrade() -> None:
    op.drop_table("fundamentals_cache")
    op.drop_table("ohlcv_daily")
    op.drop_table("symbols")
