"""Add fmp_quota_usage table for persistent daily request quota tracking.

Hand-written (not autogenerated) for full auditability.
Tracks requests made to FMP per calendar day to survive container rebuilds
and avoid exceeding the 250 requests/day free-tier quota.

Revision ID: 0002
Revises: 0001
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic
revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    op.create_table(
        "fmp_quota_usage",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "request_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("date"),
    )


def downgrade() -> None:
    op.drop_table("fmp_quota_usage")
