"""Add order_audit_logs table for Phase 9 risk engine audit trail.

Hand-written (not autogenerated) for full auditability.
Every order attempt — whether approved and dispatched, or rejected by the
risk engine — writes an immutable row here in its own committed transaction,
independent of the caller's session.

Two-phase lifecycle:
  REJECTED   — risk engine blocked the order; broker was never called.
  SUBMITTING — pre-dispatch row committed before the broker HTTP call.
  ACCEPTED   — broker accepted the order (``broker_order_id`` populated).
  FAILED     — broker call raised an exception.

Revision ID: 0003
Revises: 0002
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade() -> None:
    op.create_table(
        "order_audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("symbol", sa.String(30), nullable=False),
        sa.Column(
            "side",
            sa.String(10),
            nullable=False,
            comment="BUY or SELL",
        ),
        sa.Column("quantity", sa.Numeric(18, 6), nullable=False),
        sa.Column("entry_price", sa.Numeric(18, 6), nullable=False),
        sa.Column("stop_loss_price", sa.Numeric(18, 6), nullable=False),
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            comment="REJECTED | SUBMITTING | ACCEPTED | FAILED",
        ),
        sa.Column(
            "rejection_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'"),
        ),
        sa.Column(
            "risk_metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'"),
            comment="risk_amount, estimated_cost, binding_constraint, rule_details",
        ),
        sa.Column("broker_order_id", sa.String(100), nullable=True),
        sa.Column(
            "raw_response",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_order_audit_symbol", "order_audit_logs", ["symbol"])
    op.create_index("ix_order_audit_timestamp", "order_audit_logs", ["timestamp"])


def downgrade() -> None:
    op.drop_index("ix_order_audit_timestamp", table_name="order_audit_logs")
    op.drop_index("ix_order_audit_symbol", table_name="order_audit_logs")
    op.drop_table("order_audit_logs")
